// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGLrO3fu6roixv2UaP-XpmEUjxxXEFvKI',
    appId: '1:551388171788:web:6e5c2f328f68f77d5be829',
    messagingSenderId: '551388171788',
    projectId: 'ciclocare-7cd54',
    authDomain: 'ciclocare-7cd54.firebaseapp.com',
    storageBucket: 'ciclocare-7cd54.firebasestorage.app',
    measurementId: 'G-SCBKK8NHKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMkasWz56H2qqR_DBy03zehz4HT4caJPI',
    appId: '1:551388171788:android:e9c1cfb9ffcb62165be829',
    messagingSenderId: '551388171788',
    projectId: 'ciclocare-7cd54',
    storageBucket: 'ciclocare-7cd54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDghMumqjJvaEIyigKWGrA-i4YBHMl3eS0',
    appId: '1:551388171788:ios:ea3b5a52dfeade705be829',
    messagingSenderId: '551388171788',
    projectId: 'ciclocare-7cd54',
    storageBucket: 'ciclocare-7cd54.firebasestorage.app',
    iosBundleId: 'com.example.ciclocare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDghMumqjJvaEIyigKWGrA-i4YBHMl3eS0',
    appId: '1:551388171788:ios:ea3b5a52dfeade705be829',
    messagingSenderId: '551388171788',
    projectId: 'ciclocare-7cd54',
    storageBucket: 'ciclocare-7cd54.firebasestorage.app',
    iosBundleId: 'com.example.ciclocare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGLrO3fu6roixv2UaP-XpmEUjxxXEFvKI',
    appId: '1:551388171788:web:43f984fdf5eee4385be829',
    messagingSenderId: '551388171788',
    projectId: 'ciclocare-7cd54',
    authDomain: 'ciclocare-7cd54.firebaseapp.com',
    storageBucket: 'ciclocare-7cd54.firebasestorage.app',
    measurementId: 'G-PCPQSNQ2FB',
  );
}
